### PR TITLE
Fixed Breadcrumb outstanding issues

### LINKED ISSUE #324: Collapsed breadcrumb doesn't have hover effect
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Flutter version: [e.g. 3.20]
 - Forui version: [e.g. 0.1.0]

**Additional context**

### PR DESCRIPTION
**Pull request by Daviiddoo**
**Describe the changes**
resolves #324 

**Checklist**
- [x] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md).
- [x] I have included the relevant unit/golden tests.
- [x] I have included the relevant samples.
- [x] I have updated the documentation accordingly.
- [x] I have updated the [CHANGELOG.md](../forui/CHANGELOG.md) if necessary.

### CODE REVIEW

File: forui/lib/src/widgets/breadcrumb.dart [hunk 1]
```diff
@@ -125,11 +126,41 @@ abstract interface class FBreadcrumbItem extends Widget {
...
+        cacheExtent: cacheExtent,
+        maxHeight: maxHeight ?? double.infinity,
+        dragStartBehavior: dragStartBehavior ?? DragStartBehavior.start,
+        divider: divider ?? FTileDivider.full,
+        menuAnchor: menuAnchor,
+        childAnchor: childAnchor,
+        shift: shift ?? FPortalShift.flip,
+        hideOnTapOutside: hideOnTapOutside ?? FHidePopoverRegion.excludeTarget,
+        directionPadding: directionPadding ?? false,
+        autofocus: autofocus ?? false,
```
Comment (Pante) [inline forui/lib/src/widgets/breadcrumb.dart:160]: These default params should be declared in the constructor instead.

File: forui/lib/src/widgets/breadcrumb.dart [hunk 2]
```diff
@@ -197,7 +258,23 @@ class _CollapsedCrumb extends StatefulWidget implements FBreadcrumbItem {
   @override
   void debugFillProperties(DiagnosticPropertiesBuilder properties) {
     super.debugFillProperties(properties);
-    properties.add(DiagnosticsProperty('popOverMenuStyle', popOverMenuStyle));
+    properties
+      ..add(DiagnosticsProperty('popOverMenuStyle', popOverMenuStyle))
+      ..add(DiagnosticsProperty<FPopoverController?>('popoverController', popoverController))
+      ..add(DiagnosticsProperty<ScrollController?>('scrollController', scrollController))
```
Comment (Pante) [inline forui/lib/src/widgets/breadcrumb.dart:264]: Don't include the generics.

File: forui/lib/src/widgets/breadcrumb.dart [hunk 3]
```diff
@@ -207,24 +284,41 @@ class _CollapsedCrumbState extends State<_CollapsedCrumb> with SingleTickerProvi
   @override
   void initState() {
     super.initState();
-    controller = FPopoverController(vsync: this);
+    controller = widget.popoverController ?? FPopoverController(vsync: this);
```
Comment (Pante) [inline forui/lib/src/widgets/breadcrumb.dart:287]: You need to add a the didUpdateWidget to handle if the widget controller changes. Dispose needs to change too.

**Review by Pante — CHANGES_REQUESTED** [review]

File: forui/lib/src/widgets/breadcrumb.dart [hunk 4]
```diff
@@ -207,24 +284,41 @@ class _CollapsedCrumbState extends State<_CollapsedCrumb> with SingleTickerProvi
...
-        popoverController: controller,
-        menuAnchor: Alignment.topLeft,
-        childAnchor: Alignment.bottomLeft,
-        menu: widget.menu,
-        child: FIcon(
-          FAssets.icons.ellipsis,
-          size: style.iconStyle.size,
-          color: style.iconStyle.color,
+    final focusedOutlineStyle = context.theme.style.focusedOutlineStyle;
+    return FTappable(
```
Comment (Pante) [inline forui/lib/src/widgets/breadcrumb.dart:294]: FTappable should be wrapping the FPopover's child.

**Review by Pante — APPROVED** [review]
