### PR TITLE
Fix various issues

### LINKED ISSUE #127: FAvatar lacks semantics
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Flutter version: [e.g. 3.20]
 - Forui version: [e.g. 0.1.0]

**Additional context**

### PR DESCRIPTION
**Pull request by Pante**
This PR:
* fixes #127 
* updates themes documentation
* rename calendar controllers
* rename separator to divider

### CODE REVIEW

File: forui/lib/src/widgets/divider.dart [hunk 1]
```diff
@@ -5,25 +5,25 @@ import 'package:meta/meta.dart';
 
 import 'package:forui/forui.dart';
 
-/// A separator. Separators visually separate content.
+/// A divider. dividers visually separate content.
```
Comment (kawaijoe) [inline forui/lib/src/widgets/divider.dart:8]:
```suggestion
/// A divider. Dividers visually separate content.
```

File: docs/pages/docs/divider.mdx [hunk 2]
```diff
@@ -40,12 +40,12 @@ Visually or semantically separates content.
...
+                const FDivider(vertical: true),
                 Text(
                   'Docs',
                   style: typography.sm.copyWith(color: colorScheme.foreground),
                 ),
-                const FSeparator(vertical: true),
+                const FDivider(vertical: true),
                 Text(
                   'Source',
                   style: typography.sm.copyWith(color: colorScheme.foreground),
```
Comment (kawaijoe) [inline docs/pages/docs/divider.mdx:51]: `Usage` isn't updated. Might want to do a search on `Separator` to see if anything shows up.

File: docs/pages/docs/themes.mdx [hunk 3]
```diff
@@ -114,6 +116,24 @@ The example above uses `FThemes.zinc.light` theme as a starting point and custom
 - Remove the `borderRadius` through the style.
 - Although we removed the `borderRadius` for all widgets, override the `borderRadius` to `8` for the `FCard()` widget.
 
+<Callout type="info">
```
Comment (kawaijoe) [inline docs/pages/docs/themes.mdx:119]: I would personally use a warning here over an information.

File: forui/lib/src/widgets/avatar/avatar.dart [hunk 4]
```diff
@@ -22,25 +22,25 @@ class FAvatar extends StatelessWidget {
...
-  /// The fallback widget displayed if image parameter fails to load.
+  /// The child, typically an image.
   ///
-  /// Typically used to display the user's initials using a [Text] widget
-  /// styled with [FAvatarStyle.backgroundColor].
-  ///
-  /// Use image parameter to display an image; use [fallback] for initials.
-  final Widget fallback;
+  /// If the image fails to load, a fallback widget, typically a [Text] widget used to display the user's initials
+  /// styled with [FAvatarStyle.backgroundColor] is displayed.
```
Comment (kawaijoe) [inline forui/lib/src/widgets/avatar/avatar.dart:28]: Should this be documented here. Might be better to place it in the constructor since it's called a fallback there and the child widget here doesn't really do that as well.

File: forui/test/src/widgets/separator_golden_test.dart [hunk 5]
```diff
@@ -22,7 +22,7 @@ void main() {
                 border: Border.all(color: theme.colorScheme.secondary),
```
Comment (kawaijoe) [inline forui/test/src/widgets/separator_golden_test.dart:22]: File name is not updated. Might want to regenerate the images as well.

File: docs/pages/docs/avatar.mdx
Comment (kawaijoe) [inline docs/pages/docs/avatar.mdx:1]: Do you mind to lower case the first example comments. It's a bit strange.

`// With Valid image.` -> `// With valid image.`
Same with the bottom two other examples.

File: docs/pages/docs/avatar.mdx [hunk 6]
```diff
@@ -87,7 +87,7 @@ FAvatar.raw(child: const Text('MN'));
     </Tabs.Tab>
 </Tabs>
 
-### Without fallback
+### Without Fallback
```
Comment (kawaijoe) [inline docs/pages/docs/avatar.mdx:90]:
```suggestion
### Raw Constructor
```

File: docs/pages/docs/resizable.mdx [hunk 7]
```diff
@@ -116,14 +116,14 @@ FResizable(
 
 ## Examples
 
-### Cascading
+### No Cascading
```
Comment (kawaijoe) [inline docs/pages/docs/resizable.mdx:119]:
```suggestion
### Without Cascading
```

Nitpick, but I think throughout the docs, we tend to use with/without.

File: docs/pages/docs/resizable.mdx [hunk 8]
```diff
@@ -281,14 +282,14 @@ FResizable(
   </Tabs.Tab>
 </Tabs>
 
-### No divider
+### No Divider
```
Comment (kawaijoe) [inline docs/pages/docs/resizable.mdx:285]:
```suggestion
### Without Divider
```

File: docs/pages/docs/avatar.mdx [hunk 9]
```diff
@@ -13,7 +13,7 @@ An image element with a fallback for representing the user.
       Row(
         mainAxisAlignment: MainAxisAlignment.center,
         children: [
-          // With Valid image.
+          // With valid image.
           FAvatar(
             image: const NetworkImage('https://raw.githubusercontent.com/forus-labs/forui/main/samples/assets/avatar.png'),
             fallback: const Text('MN'),
```
Comment (kawaijoe) [inline docs/pages/docs/avatar.mdx:19]: I think you missed out the `Invalid` below

Comment (Pante) [reply docs/pages/docs/avatar.mdx:19]: reeeee
